### ISSUE TITLE
Service Wrappers are not generated

### ISSUE THREAD

**Issue by agearhart** [vizor-games/infraworld-cornerstone#5]
Given the attached config.yml and proto files only the UE4 classes are generated and not the service wrappers as expected.  Any help would be appreciated.
[BuildInfo.proto.txt](https://github.com/vizor-games/infraworld-cornerstone/files/2778927/BuildInfo.proto.txt)

[config.yml.txt](https://github.com/vizor-games/infraworld-cornerstone/files/2778928/config.yml.txt)

**Comment by RChehowski** [comment]
Hi there @agearhart! Currently our software can only generate UE4-support classes, so you have to generate your xxx.grpc.pb.h and xxx.pb.h by hand using protoc and plugins (get them pre-built [here](https://github.com/vizor-games/InfraworldRuntime/releases)) or use [our fancy tool](https://github.com/vizor-games/infraworld-protobuild) to automate service wrapper generation. Feel free to add extra comments if you more information. Best.

**Comment by agearhart** [comment]
Fancy tool it is then.  Thanks!
